AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Metrics/ClassLength:
  Enabled: false